### ISSUE TITLE
菜鸟一枚，能麻烦您指导下怎么用吗（龇牙

### ISSUE THREAD

**Issue by Pex-github** [chouchouxsl/crawling-word-book#1]
你好，我是一个菜鸟，刚接触github，同时在使用不背单词，因为录入单词麻烦，所以看到您优秀方便项目。我安装好了node.js。然后启用cmd，输入您的代码模板，出现错误：cannot find module 'axios'。我用npm下载了axios，还是错误，一样。我是纯纯菜鸟。如果您有时间回复，那么非常感谢❤

**Comment by Pex-github** [comment]
问题解决了，卡壳了着急，打扰了大佬，感谢你的项目，给予了我很大的帮助，我在努力学习中，祝你身体健康，万事如意

**Comment by Pex-github** [comment]
> 你好，我是一个菜鸟，刚接触github，同时在使用不背单词，因为录入单词麻烦，所以看到您优秀方便项目。我安装好了node.js。然后启用cmd，输入您的代码模板，出现错误：cannot find module 'axios'。我用npm下载了axios，还是错误，一样。我是纯纯菜鸟。如果您有时间回复，那么非常感谢❤

**Comment by chouchouxsl** [comment]
> 问题解决了，卡壳了着急，打扰了大佬，感谢你的项目，给予了我很大的帮助，我在努力学习中，祝你身体健康，万事如意

这个就是个小脚本  自己用来获取单词本的  感谢你的喜欢~
